# Aufgabe 1

In [10]:
import numpy as np

def array_info(array: np.array) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

### a)

In [11]:
A=np.array([1,4,0,1])
B=np.array([1,0,3,2])

X=np.multiply(A, np.transpose(B))

print(X)

[1 0 0 2]


### b)

In [12]:
a=np.array([[1],[4],[0],[1]])
b=np.array([[1,0],[0,1],[3,4],[2,0]])

x=np.multiply(a, b)

print(x)

[[1 0]
 [0 4]
 [0 0]
 [2 0]]


### c)

In [13]:
a=np.array([[1,4,0,1],[0,2,1,3]])

b=np.array([[1,0],[0,1],[3,4],[2,0]])
x=np.matmul(a,b)

print(x)

[[3 4]
 [9 6]]


### d)

In [14]:
a=np.array([[1,4,0,1],[0,2,1,3]])

b=np.array([[1,0,3],[0,1,1],[3,4,1],[2,0,1]])
x=np.matmul(a,b)

print(x)

[[3 4 8]
 [9 6 6]]


### e)

In [15]:
#a=np.array([[1,0,0],[0,1,0],[0,0,1]])
a=np.eye(N=3)

b=np.array([[1,4,7],[2,5,8],[3,6,9]])
x=np.matmul(a,b)

print(x)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


### f)

In [16]:
#a=np.array([[1,0,0],[0,1,0],[0,0,1]])
b=np.eye(N=3)

a=np.array([[1,4,7],[2,5,8],[3,6,9]])
x=np.matmul(a,b)

print(x)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


### g)

In [17]:
a=np.array([[1,0,0],[1,0,0],[1,0,0]])

b=np.array([[1,4,7],[2,5,8],[3,6,9]])
x=np.matmul(a,b)

print(x)

[[1 4 7]
 [1 4 7]
 [1 4 7]]


### h)

In [18]:
a=np.array([[1,0,0],[1,0,0],[1,0,0]])

b=np.array([[1,4,7],[2,5,8],[3,6,9]])
x=np.matmul(a,b)

print(x)

[[1 4 7]
 [1 4 7]
 [1 4 7]]


# Aufgabe 2

## a)

In [27]:
A=np.array([[-2,0],[-1,3],[4,1]])
B=np.array([[-1,1],[5,3]])
C=np.array([[2,-3],[1,0]])

X=np.matmul(A,B+C)
B+C
print(X)

[[-2  4]
 [17 11]
 [10 -5]]


## b)

In [28]:
A=np.array([[-2,0],[-1,3],[4,1]])
B=np.array([[-1,1],[5,3]])
C=np.array([[2,-3],[1,0]])

X=np.matmul(A,B)+np.matmul(A,C)
print(X)

[[-2  4]
 [17 11]
 [10 -5]]


# Aufgabe 3
## a)

In [29]:
A=np.array([[1,2],[3,4]])
B=np.array([[-1,2],[-1,1]])

X=np.transpose(B)*np.transpose(A)
print(X)

[[-1 -3]
 [ 4  4]]


## b)

In [30]:
A=np.array([[1,2],[3,4]])
B=np.array([[-1,2],[-1,1]])

X=np.transpose(np.matmul(A,B))
print(X)

[[-3 -7]
 [ 4 10]]


## c)

In [31]:
A=np.array([[1,2],[3,4]])
B=np.array([[-1,2],[-1,1]])

X=np.transpose(A)*np.transpose(B)
print(X)

[[-1 -3]
 [ 4  4]]


## d)

In [32]:
A=np.array([[1,2],[3,4]])
B=np.array([[-1,2],[-1,1]])

X=np.transpose(A+B)
print(X)

[[0 2]
 [4 5]]


## e)

In [33]:
A=np.array([[1,2],[3,4]])
B=np.array([[-1,2],[-1,1]])

X=np.transpose(2*A)
print(X)

[[2 6]
 [4 8]]


## f)

In [34]:
A=np.array([[1,2],[3,4]])
B=np.array([[-1,2],[-1,1]])

X=np.transpose(2*B)
print(X)

[[-2 -2]
 [ 4  2]]


# Zusatzaufgabe

Verwende ufunction wie matmul, multiply, sum etc...

# Zusatzaufgabe

In [35]:
A=np.array([[1,2],[3,4]])
B=np.array([[-1,2],[-1,1]])

X=np.linalg.det(A)
print(X)

-2.0000000000000004
