In [50]:
import numpy as np
import math as math

A = np.zeros(shape=(3,3), dtype=float)

A = np.diag([math.pi,math.pi,math.pi])

i = np.triu_indices(3,1)
A[i] = 1

i = np.tril_indices(3,-1)
A[i] = -1


print(A)



[[ 3.14159265  1.          1.        ]
 [-1.          3.14159265  1.        ]
 [-1.         -1.          3.14159265]]


In [64]:
a = np.zeros(shape=(5,5), dtype=int)

a[::1,::4]=1
a[::4,::1]=1

print (a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [92]:
a = np.zeros(shape=(8,8),dtype=int)

a[::2,::2] = 1
a[::-2,::-2] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [115]:
import numpy as np
np.random.seed(0)
M = np.array(np.random.randint(low=-10, high=11, size=(5, 5), dtype='h'))
N = np.array(np.random.uniform(low=-10, high=10, size=(5, 5)))

n = np.multiply(N,math.pi)

n = np.cos(n)

m = np.abs(M)

print(m)


[[ 2  5  6 10  9]
 [ 7  4  8  7  3]
 [ 5  1 10  9  9]
 [ 8  4  6  5  1]
 [ 4  1  6  8  2]]


In [62]:
import numpy as np
a = np.ones(shape=(8,8),dtype=int)

b = np.array([2,2,2,2,2,2,2,2])
a= np.diag(b)

i = np.tril_indices(6,-1)
a[i] = 1


i = np.triu_indices(6,1)
a[i] = 1


print(a)

[[2 1 1 1 1 1 0 0]
 [1 2 1 1 1 1 0 0]
 [1 1 2 1 1 1 0 0]
 [1 1 1 2 1 1 0 0]
 [1 1 1 1 2 1 0 0]
 [1 1 1 1 1 2 0 0]
 [0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 2]]
