## Numpy Basics

NumPy stellt einen N-dimensionalen Array-Typ bereit, den ndarray.
Es beschreibt eine Sammlung von „Elementen“ desselben Typs.
Die Elemente können beispielsweise mit N Ganzzahlen indiziert werden.
Alle Ndarrays sind homogen: Jedes Element belegt den gleichen Speicherblock.
Ein Element aus dem Array wird durch ein PyObject dargestellt, das einer der integrierten NumPy-Skalartypen ist.

<p align="left">
<img src="https://numpy.org/doc/stable/_images/threefundamental.png">
</p>


## Numpy Array Attributes

In [1]:
import numpy as np


np.random.seed(0)       # Funktion mit der wir immer die gleichen Zufallszahlen generieren können

In [2]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

## Array Indexing and Sclicing


Unter Array-Indizierung versteht man die Verwendung der eckigen Klammern ([]) zur Indizierung von Array-Werten.
Es gibt viele Optionen für die Indizierung, die der Numpy-Indizierung große Leistungsfähigkeit verleihen.

Die meisten der folgenden Beispiele zeigen die Verwendung der Indizierung beim Verweisen auf Daten in einem Array.
Die Beispiele funktionieren genauso gut bei der Zuweisung zu einem Array.

Hinweis: Array-Slices kopieren nicht die internen Array-Daten, sondern erzeugen nur neue Ansichten der Daten.

![Alt text](np_matrix_indexing.png)



In [3]:
x = np.array([[1, 2], [3, 4], [5, 6]])

array_info(x)

ndim: 2
shape: (3, 2)
size: 6
dtype: int32
values:
[[1 2]
 [3 4]
 [5 6]]



In [4]:
print(x[:3])

[[1 2]
 [3 4]
 [5 6]]


In [5]:
print(x[1:])

[[3 4]
 [5 6]]


In [6]:
print(x[1:2])

[[3 4]]


In [7]:
print(x[::-1])

[[5 6]
 [3 4]
 [1 2]]


In [ ]:
print(x[0, :])

In [ ]:
print(x[0])

In [ ]:
print(x[:, 0])

In [4]:
x[x>2]=-1
print(x)

[[ 1  2]
 [-1 -1]
 [-1 -1]]


In [ ]:
y=np.multiply(2,x)
print(y)

## Ufunctions

Eine universelle Funktion ist eine Funktion:

- das auf ndarrays Element für Element arbeitet

Ein ufunc ist ein „vektorisierter“ Wrapper für eine Funktion, die ausgeführt wird
eine feste Anzahl spezifischer Eingaben und erzeugt eine feste Anzahl spezifischer Ausgaben.

In [ ]:
from typing import Iterable

import numpy as np


np.random.seed(0)

### Native Python Loops

In [ ]:
def reciprocal(values: Iterable[float]) -> Iterable[float]:
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [ ]:
small_array = np.random.randint(low=1, high=10, size=5)
print(reciprocal(small_array))

In [ ]:
small_array = np.random.randint(low=1, high=10, size=5)

%timeit reciprocal(small_array)

In [ ]:
big_array = np.random.randint(low=1, high=10, size=100_000)

%timeit reciprocal(big_array)

Geschwindigkeitsvergleich bei Faktor 10.000 
(Python skaliert die Werte nicht ganz linear)

In [ ]:
149 * 1000 / 8.34

## Einführung Ufunction

In [ ]:
print(reciprocal(small_array))
print(1.0 / small_array)

In [ ]:
%timeit (1.0 / big_array)

In [ ]:
%timeit np.reciprocal(big_array)

### Vergleich Iterativer Prozess und Ufunctions

Geschwindigkeitsvergleich zwischen Iterativen Prozess und Ufunction
(iterativ)*1000 /ufunction

In [ ]:
#200 * 1000 / 103 
149 * 1000 /104 #Geschwindigkeit

## Welche Ufunctions gibt es?

In [ ]:
x = np.arange(4)

print(x)

In [ ]:
print(x + 2)
print(x - 2)
print(x * 2)
print(x / 2)

In [ ]:
print(np.add(x, 2))

### Standardfunktionen

| Name       | Beschreibung                                                   |
| ---------- | ------------------------------------------------------------- |
| add        | Adds, element-wise                                            |
| subtract   | Subtracts, element-wise                                       |
| multiply   | Multiplies, element-wise                                      |
| matmul     | Matrix product of two arrays                                  |
| divide     | Returns a true division of the inputs, element-wise           |
| negative   | Numerical negative, element-wise                              |
| positive   | Numerical positive, element-wise                              |
| mod        | Return, element-wise remainder of division                    |
| absolute   | Calculate the absolute value, element-wise                    |
| fabs       | Compute the absolute values, element-wise                     |
| sign       | Returns an, element-wise indication of the sign of a number   |
| exp        | Calculate the exponential of all elements in the input array  |
| log        | Natural logarithm, element-wise                               |
| sqrt       | Return the non-negative square-root of an array, element-wise |
| square     | Return the, element-wise square of the input                  |
| reciprocal | Return the reciprocal of the argument, element-wise           |
| gcd        | Returns the greatest common divisor of \|x1\| and \|x2\|      |
| lcm        | Returns the lowest common multiple of \|x1\| and \|x2\|       |

### Trigonometrische Funktionen

| Name | Beschreibung                      |
| ---- | -------------------------------- |
| sin  | Trigonometric sine, element-wise |
| cos  | Cosine, element-wise             |
| tan  | Compute tangent, element-wise    |

### Vergleichsfunktionen

| Name          | Beschreibung                                       |
| ------------- | -------------------------------------------------- |
| greater       | Return the truth value of (x1 > x2), element-wise  |
| greater_equal | Return the truth value of (x1 >= x2), element-wise |
| less          | Return the truth value of (x1 < x2), element-wise  |
| less_equal    | Return the truth value of (x1 <= x2), element-wise |
| not_equal     | Return (x1 != x2), element-wise                    |
| equal         | Return (x1 == x2), element-wise                    |


In [ ]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)
print(np.abs(x))
print(np.fabs(x))

In [ ]:
theta = np.linspace(0, 2.0 * np.pi, 7)

print(theta)
print(np.sin(theta))
print(np.cos(theta))

In [ ]:
print(np.greater([4, 2], [2, 2]))

a = np.array([4, 2])
b = np.array([2, 2])
print(a > b)