In [16]:
import numpy as np

N = np.zeros((3,3))


M = np.array([np.pi,np.pi,np.pi])
N= np.diag(M)


N[1,0] = -1

i =  np.tril_indices(3,-1)
j =  np.triu_indices(3,1)
print (i)
#N[i]= -1


#print (N)

(array([1, 2, 2]), array([0, 0, 1]))


In [85]:
import numpy as np

N = np.array(np.zeros((5,5)))
#N[Zeile,Spalte]
N[::1,::4] = 1
N[::4,::1] = 1

M = np.array(np.ones((5,5)))
#oder
M[1:4,1:4] = 0
print (M)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [1]:
#Aufgabe 3
import numpy as np
N = np.array(np.zeros((8,8)))

N[::2,::2] = 1
N[::-2,::-2] = 1

print (N)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [1]:
#Aufgabe 4

import numpy as np


np.random.seed(0)


M = np.array(np.random.randint(low=-10, high= 11, size=(5,5), dtype='h')) #15
N = np.array(np.random.uniform(low= -10, high=10, size=(5,5))) #10

m = np.count_nonzero(M<0)
n = np.count_nonzero(N<0)

print ("Zahlen unter 0 bei M: ",m)
print ("Zahlen unter 0 bei N: ",n)

Zahlen unter 0 bei M:  15
Zahlen unter 0 bei N:  10


In [138]:
#Aufgabe 5

import numpy as np


np.random.seed(0)



M = np.array(np.random.randint(low=-10, high= 11, size=(5,5), dtype='h')) #15
N = np.array(np.random.uniform(low= -10, high=10, size=(5,5))) #10

M[M < 0] = 0
N[N<0] = 0

print (M)


    
    



[[ 2  5  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0 10  9  0]
 [ 8  0  0  0  1]
 [ 0  1  0  8  2]]


In [140]:
#Aufgabe 6
N = np.multiply(N,np.pi)
print (N)

N = np.cos(N)
print(N)

[[ 0.         57.5842144   5.70362854 13.43145799 84.00940909]
 [ 0.          0.          0.         65.65652583 54.90594187]
 [73.03747054 94.47547394 59.05153364  0.         55.37423986]
 [ 0.         27.61930256  0.         87.77412601  4.31268585]
 [ 0.          0.         54.13156056  0.         13.50832006]]
[[ 1.          0.51005583  0.83670547  0.64857361 -0.68689194]
 [ 1.          1.          1.         -0.95019981 -0.07186756]
 [-0.71032288  0.97418945 -0.80285547  1.          0.38607088]
 [ 1.         -0.79302885  1.          0.98191569 -0.38914489]
 [ 1.          1.         -0.74884054  1.          0.58821262]]
