In [1]:
import numpy as np

# Aufgabe a

a = np.array([[1,2],[3,4]])
b = np.array([[-1,2],[-3,1]])


print(np.transpose(b) @ np.transpose(a))

[[ -7 -15]
 [  4  10]]


In [2]:
import numpy as np

# Aufgabe b

a = np.array([[1,2],[3,4]])
b = np.array([[-1,2],[-3,1]])


print(np.transpose(a @ b))

[[ -7 -15]
 [  4  10]]


In [3]:
import numpy as np

# Aufgabe c

a = np.array([[1,2],[3,4]])
b = np.array([[-1,2],[-3,1]])


print(np.transpose(a) @ np.transpose(b))

[[ 5  0]
 [ 6 -2]]


In [4]:
import numpy as np

# Aufgabe d

a = np.array([[1,2],[3,4]])
b = np.array([[-1,2],[-3,1]])


print(np.transpose(a + b))

[[0 0]
 [4 5]]


In [5]:
import numpy as np

# Aufgabe e

a = np.array([[1,2],[3,4]])
b = np.array([[-1,2],[-3,1]])


print(np.transpose(2 * a))

[[2 6]
 [4 8]]


In [6]:
import numpy as np

# Aufgabe f

a = np.array([[1,2],[3,4]])
b = np.array([[-1,2],[-3,1]])


print(np.transpose(2 * b))

[[-2 -6]
 [ 4  2]]
