In [1]:
import numpy as np

# Aufgabe a

a = np.array([1,4,0,1])
b = np.array([[1],[0],[3],[2]])

print(a @ b)


[3]


In [5]:
import numpy as np

# Aufgabe b

a = np.array([1,4,0,1])
b = np.array([[1,0],[0,1],[3,4],[2,0]])

print(a @ b)

[3 4]


In [7]:
import numpy as np

# Aufgabe c

a = np.array([[1,4,0,1],[0,2,1,3]])
b = np.array([[1,0],[0,1],[3,4],[2,0]])

print(a @ b)

[[3 4]
 [9 6]]


In [8]:
import numpy as np

# Aufgabe d

a = np.array([[1,4,0,1],[0,2,1,3]])
b = np.array([[1,0,3],[0,1,1],[3,4,1],[2,0,1]])

print(a @ b)

[[3 4 8]
 [9 6 6]]


In [9]:
import numpy as np

# Aufgabe e

a = np.array([[1,0,0],[0,1,0],[0,0,1]])
b = np.array([[1,4,7],[2,5,8],[3,6,9]])

print(a @ b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
import numpy as np

# Aufgabe f


a = np.array([[1,4,7],[2,5,8],[3,6,9]])
b = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(a @ b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
import numpy as np

# Aufgabe g

a = np.array([[1,0,0],[1,0,0],[1,0,0]])
b = np.array([[1,4,7],[2,5,8],[3,6,9]])


print(a @ b)

[[1 4 7]
 [1 4 7]
 [1 4 7]]


In [12]:
import numpy as np

# Aufgabe h

a = np.array([[1,4,7],[2,5,8],[3,6,9]])
b = np.array([[1,0,0],[1,0,0],[1,0,0]])



print(a @ b)

[[12  0  0]
 [15  0  0]
 [18  0  0]]
