# Matrizen und Vektoren mit Numpy in Python programmieren

## Listen und Arrays in Python


In [2]:
import numpy as np

In [3]:
import array

import numpy as np

Numpy ist ein Akronym für "Nummerisches Python". Diese Erweiterung ist zum größten Teil in C geschrieben und stellt dadurch sicher, dass ie kompilierten mathematischen und numerischen Funktionen und Funktionalitäten eine größtmögliche Ausführungsgeschwindigkeit garantieren. Standardmäßig wird Numpy mit np abgekürzt.

Der Installationspfad zum installieren an den Schulrechnern lautet:

"C:\Program Files\Python310\python.exe" -m  pip  install numpy

## Listen in Python

In [4]:
my_list = [True, "Hello", 42.0, 420, None]

print([type(val) for val in my_list])


[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>, <class 'NoneType'>]


## Python Array

In [5]:
my_array_range = list(range(10))
my_array = array.array('i', my_array_range)

print(my_array)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Array Dtypes

|           |                    |                   |                       |     |
| --------- | ------------------ | ----------------- | --------------------- | --- |
| Type code | C Type             | Python Type       | Minimum size in bytes |
| 'b'       | signed char        | int               | 1                     |
| 'B'       | unsigned char      | int               | 1                     |
| 'u'       | wchar_t            | Unicode character | 2                     |
| 'h'       | signed short       | int               | 2                     |
| 'H'       | unsigned short     | int               | 2                     |
| 'i'       | signed int         | int               | 2                     |
| 'I'       | unsigned int       | int               | 2                     |
| 'l'       | signed long        | int               | 4                     |
| 'L'       | unsigned long      | int               | 4                     |
| 'q'       | signed long long   | int               | 8                     |
| 'Q'       | unsigned long long | int               | 8                     |
| 'f'       | float              | float             | 4                     |
| 'd'       | double             | float             | 8                     |


In [6]:
my_array_range = list(range(10))
my_array = array.array('d', my_array_range)

print(my_array)

array('d', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])


## Numpy Array

NumPy ist das grundlegende Paket für wissenschaftliches Rechnen in Python.
Es handelt sich um eine Python-Bibliothek, die ein mehrdimensionales Array-Objekt bereitstellt.
verschiedene abgeleitete Objekte und eine Reihe von Routinen für
schnelle Operationen auf Arrays.

Das Herzstück des NumPy-Pakets ist das ndarray-Objekt.
Dies kapselt n-dimensionale Arrays homogener Datentypen.
wobei viele Vorgänge aus Leistungsgründen im kompilierten Code ausgeführt werden.

Wir definieren eine Funktion, die uns die wesentlichen Größen eines Arrays liefert:

In [7]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

In [8]:
my_np_array = np.array([1, 4, 2, 5, 3])
array_info(my_np_array)

ndim: 1
shape: (5,)
size: 5
dtype: int32
values:
[1 4 2 5 3]



In [9]:
my_np_array = np.array([3.14, 4, 2, 3])
array_info(my_np_array)


ndim: 1
shape: (4,)
size: 4
dtype: float64
values:
[3.14 4.   2.   3.  ]



In [10]:
my_np_array = np.array([1, 2, 3, 4], dtype='float32')
array_info(my_np_array)

ndim: 1
shape: (4,)
size: 4
dtype: float32
values:
[1. 2. 3. 4.]



## Numpy Funktionen


### Nullmatrix erstellen

In [11]:
my_np_array = np.zeros(shape=(10), dtype=int)
array_info(my_np_array)

ndim: 1
shape: (10,)
size: 10
dtype: int32
values:
[0 0 0 0 0 0 0 0 0 0]



### Einsmatrix

In [12]:
my_np_array = np.ones(shape=(3, 5), dtype=float)
array_info(my_np_array)

ndim: 2
shape: (3, 5)
size: 15
dtype: float64
values:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



### Erzeugen einer Matrix mit gleichen Komponenten

In [13]:
my_np_array = np.full(shape=(3, 5), fill_value=3.14)
array_info(my_np_array)

ndim: 2
shape: (3, 5)
size: 15
dtype: float64
values:
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]



### Erstellen eines Vektors mit Start-, Stopwert und Schrittweite

In [14]:
my_np_array = np.arange(start=0, stop=20, step=2)
array_info(my_np_array)

ndim: 1
shape: (10,)
size: 10
dtype: int32
values:
[ 0  2  4  6  8 10 12 14 16 18]



### Erstellen eines Vektor mit Start-, Stopwert sowie Anzahl der Elemente zwischen diesen Werten

In [15]:
my_np_array = np.linspace(start=0, stop=1, num=5)
array_info(my_np_array)

ndim: 1
shape: (5,)
size: 5
dtype: float64
values:
[0.   0.25 0.5  0.75 1.  ]



### Erstellen einer Einheitsmatrix

In [16]:
my_np_array = np.eye(N=3)
array_info(my_np_array)

ndim: 2
shape: (3, 3)
size: 9
dtype: float64
values:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



### Erstellen einer Diagnoalmatrix

In [17]:
my_np_array = np.diag([1, 2, 3])
array_info(my_np_array)

ndim: 2
shape: (3, 3)
size: 9
dtype: int32
values:
[[1 0 0]
 [0 2 0]
 [0 0 3]]



## Random Funktionen

### Ganzzahl Zufallszahl

In [18]:
my_np_array = np.random.randint(low=0, high=10, size=(3, 3))
array_info(my_np_array)

ndim: 2
shape: (3, 3)
size: 9
dtype: int32
values:
[[4 7 8]
 [2 9 9]
 [4 4 7]]



### Reelle Zufallszahl

In [19]:
my_np_array = np.random.random(size=(3, 3))
array_info(my_np_array)


ndim: 2
shape: (3, 3)
size: 9
dtype: float64
values:
[[0.41085025 0.76310947 0.31047541]
 [0.5874872  0.23099643 0.68777054]
 [0.13104996 0.22085346 0.76468711]]

